<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition="'$(EnableNet11)' == 'true'">net11.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <NoWarn>$(NoWarn);CA1822;CA1051;CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tedd.FastNoise\Tedd.FastNoise.csproj" />
    <ProjectReference Include="..\..\archive\v1\Tedd.FastNoise.V1\Tedd.FastNoise.V1.csproj" />
  </ItemGroup>

</Project>
