using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;

namespace Tedd.FastNoise.Gallery;

/// <summary>
/// Renders the sample images used on the documentation site.
/// </summary>
/// <remarks>
/// Run by the Pages workflow so the gallery is always generated by the code it documents, rather
/// than being a set of committed PNGs that quietly stop matching what the library does.
/// </remarks>
internal static class Program
{
    private const int Size = 420;

    private static int Main(string[] args)
    {
        string output = args.Length > 0 ? args[0] : "gallery";
        Directory.CreateDirectory(output);

        foreach ((string name, Func<float[]> render, Palette palette) in Samples())
        {
            Stopwatch clock = Stopwatch.StartNew();
            float[] field = render();
            clock.Stop();

            Png.Write(Path.Combine(output, name + ".png"), Size, Size, Colourise(field, palette));
            Console.WriteLine($"{name,-22} {Size}x{Size} in {clock.Elapsed.TotalMilliseconds:0.0} ms");
        }

        Console.WriteLine($"Wrote gallery to {Path.GetFullPath(output)}");
        return 0;
    }

    private static IEnumerable<(string Name, Func<float[]> Render, Palette Palette)> Samples()
    {
        yield return ("opensimplex2", () => new NoiseGenerator(1337)
        {
            NoiseType = NoiseType.OpenSimplex2,
            FractalType = FractalType.FBm,
            Octaves = 5,
            Frequency = 0.01f,
        }.Create(new GridRegion2D(0, 0, Size, Size)), Palette.Grey);

        yield return ("ridged", () => new NoiseGenerator(4242)
        {
            NoiseType = NoiseType.OpenSimplex2,
            FractalType = FractalType.Ridged,
            Octaves = 6,
            Frequency = 0.006f,
        }.Create(new GridRegion2D(0, 0, Size, Size)), Palette.Grey);

        yield return ("cellular", () => new NoiseGenerator(7)
        {
            NoiseType = NoiseType.Cellular,
            CellularDistanceFunction = CellularDistanceFunction.Euclidean,
            CellularReturnType = CellularReturnType.Distance2Sub,
            Frequency = 0.03f,
        }.Create(new GridRegion2D(0, 0, Size, Size)), Palette.Grey);

        yield return ("layered-world", BuildWorld, Palette.Terrain);

        yield return ("lod-close", () => BuildLodStack().Create(new GridRegion2D(0, 0, Size, Size, 1f)), Palette.Terrain);
        yield return ("lod-far", () => BuildLodStack().Create(new GridRegion2D(0, 0, Size, Size, 64f)), Palette.Terrain);
    }

    /// <summary>The layered world from the README, rendered as a map.</summary>
    private static float[] BuildWorld()
    {
        NoiseStack stack = new();

        stack.Add(new NoiseLayer
        {
            Source = new NoiseGenerator(1337) { Frequency = 0.004f, FractalType = FractalType.FBm, Octaves = 5 },
            Name = "continents",
        });

        stack.Add(new NoiseLayer
        {
            Source = new NoiseGenerator(90210) { Frequency = 0.012f, FractalType = FractalType.Ridged, Octaves = 5 },
            Blend = LayerBlend.Add,
            Amplitude = 0.35f,
            Name = "mountains",
        });

        stack.Add(new NoiseLayer
        {
            Source = new NoiseGenerator(555) { Frequency = 0.12f, NoiseType = NoiseType.Value },
            Blend = LayerBlend.Add,
            Amplitude = 0.05f,
            Name = "surface detail",
        });

        return stack.Compile().Create(new GridRegion2D(0, 0, Size, Size));
    }

    /// <summary>An eight-octave world with level of detail on, for the close/far comparison.</summary>
    private static CompiledNoiseStack BuildLodStack()
    {
        NoiseStack stack = new() { Lod = LodPolicy.Automatic with { CullLayers = true } };

        stack.Add(new NoiseLayer
        {
            Source = new NoiseGenerator(11) { Frequency = 0.0004f, FractalType = FractalType.FBm, Octaves = 8 },
            FeatureSize = 500f,
            Name = "continents",
        });

        stack.Add(new NoiseLayer
        {
            Source = new NoiseGenerator(12) { Frequency = 0.02f, NoiseType = NoiseType.Value },
            Amplitude = 0.08f,
            FeatureSize = 16f,
            Name = "surface",
        });

        return stack.Compile();
    }

    private enum Palette
    {
        Grey,
        Terrain,
    }

    private static byte[] Colourise(float[] field, Palette palette)
    {
        byte[] rgb = new byte[field.Length * 3];

        for (int index = 0; index < field.Length; index++)
        {
            float unit = Math.Clamp((field[index] + 1f) * 0.5f, 0f, 1f);
            (byte r, byte g, byte b) = palette == Palette.Terrain ? Terrain(unit) : (Grey(unit), Grey(unit), Grey(unit));

            rgb[(index * 3) + 0] = r;
            rgb[(index * 3) + 1] = g;
            rgb[(index * 3) + 2] = b;
        }

        return rgb;
    }

    private static byte Grey(float unit) => (byte)(unit * 255f);

    private static (byte, byte, byte) Terrain(float unit) => unit switch
    {
        < 0.36f => Mix((12, 28, 78), (28, 86, 160), unit / 0.36f),
        < 0.48f => Mix((28, 86, 160), (86, 160, 208), (unit - 0.36f) / 0.12f),
        < 0.52f => Mix((214, 205, 158), (196, 184, 126), (unit - 0.48f) / 0.04f),
        < 0.68f => Mix((92, 142, 74), (60, 108, 52), (unit - 0.52f) / 0.16f),
        < 0.84f => Mix((104, 100, 92), (140, 136, 128), (unit - 0.68f) / 0.16f),
        _ => Mix((190, 190, 190), (255, 255, 255), (unit - 0.84f) / 0.16f),
    };

    private static (byte, byte, byte) Mix((int R, int G, int B) from, (int R, int G, int B) to, float t)
    {
        t = Math.Clamp(t, 0f, 1f);
        return (
            (byte)(from.R + ((to.R - from.R) * t)),
            (byte)(from.G + ((to.G - from.G) * t)),
            (byte)(from.B + ((to.B - from.B) * t)));
    }
}
